# apiVersion: opentelemetry.io/v1alpha1
# kind: Instrumentation
# metadata:
#   name: spring-auto
#   namespace: observability
# spec:
#   exporter:
#     endpoint: http://otel-collector.observability:4317
#   propagators: [tracecontext, baggage, b3]
#   sampler:
#     type: parentbased_traceidratio
#     argument: "1.0"
#   java:
#     image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java:latest
#   env:
#     - name: OTEL_EXPORTER_OTLP_PROTOCOL
#       value: grpc
#     - name: OTEL_METRICS_EXPORTER
#       value: otlp
#     - name: OTEL_LOGS_EXPORTER
#       value: none
#     - name: OTEL_RESOURCE_ATTRIBUTES
#       value: service.version=1.0.0,deployment.environment=dev
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: java-instrumentation
spec:
  exporter:
    endpoint: http://otel-collector.observability:4317
  sampler:
    type: parentbased_traceidratio
    argument: "0.2"
  java:
    env:
      - name: OTEL_METRICS_EXPORTER
        value: otlp
      - name: OTEL_TRACES_EXPORTER
        value: otlp
      - name: OTEL_LOGS_EXPORTER
        value: otlp
      - name: OTEL_JAVAAGENT_EXTENSIONS
        value: ""
      - name: OTEL_INSTRUMENTATION_COMMON_DEFAULT_ENABLED
        value: "true"

